In [1]:
import pandas as pd
from pathlib import Path

In [2]:
DATA_PATH = Path(r"C:\Users\user\Documents\new fake news\NLP_Group_05\data")

fake_file = DATA_PATH / "Fake.csv"
true_file = DATA_PATH / "True.csv"

In [3]:
fake_news = pd.read_csv(fake_file)
true_file = next(DATA_PATH.glob("True.csv"), None)
if true_file is None:
    true_file = next(DATA_PATH.glob("true.csv"), None)

if true_file is None:
    true_file = next(DATA_PATH.glob("Real.csv"), None)
    if true_file is None:
        true_file = next(DATA_PATH.glob("real.csv"), None)

    if true_file is None:
        raise FileNotFoundError(
            f"Could not find True.csv or Real.csv in {DATA_PATH}. "
            f"Available files: {[p.name for p in DATA_PATH.iterdir()]}"
        )

true_news = pd.read_csv(true_file)

print("Fake dataset shape:", fake_news.shape)
print("True dataset shape:", true_news.shape)

Fake dataset shape: (23481, 4)
True dataset shape: (21417, 4)

In [4]:
display(fake_news.head())
display(true_news.head())

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
fake_news["label"] = 0
true_news["label"] = 1

In [6]:
combined_data = pd.concat(
    [fake_news, true_news],
    ignore_index=True
)

print("Total records:", combined_data.shape[0])
display(combined_data.head())

Total records: 44898

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [7]:
print("Missing values:")
print(combined_data.isnull().sum())

print("\nClass distribution:")
print(combined_data["label"].value_counts())

print("\nDuplicate rows:")
print(combined_data.duplicated().sum())

Missing values:
title      0
text       0
subject    0
date       0
label      0
dtype: int64

Class distribution:
label
0    23481
1    21417
Name: count, dtype: int64

Duplicate rows:
209

In [8]:
output_path = Path("../data/processed/combined_news.csv")

output_path.parent.mkdir(parents=True, exist_ok=True)

combined_data.to_csv(output_path, index=False)

print("Saved successfully to:", output_path)

Saved successfully to: ..\data\processed\combined_news.csv